-- CÂU 1
CREATE DATABASE QLHANG
GO
USE QLHANG
GO

CREATE TABLE VATTU(
    MAVT varchar(10) PRIMARY KEY, 
    TENVT nvarchar(50),
    DVTINH nvarchar(50),
    SLCON INT
);

CREATE TABLE HDBAN(
    MAHD varchar(10) PRIMARY KEY, 
    NGAYXUAT DATE,
    HOTENKHACH nvarchar(50)
);

CREATE TABLE HANGXUAT(
    MAHD varchar(10),
    MAVT varchar(10),
    DONGIA INT,
    SLBAN INT,
    CONSTRAINT HANGXUAT_PK PRIMARY KEY (MAHD, MAVT)
);

ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_HDBAN
FOREIGN KEY (MAHD) REFERENCES HDBAN (MAHD);
ALTER TABLE HANGXUAT ADD CONSTRAINT FK_HANGXUAT_VATTU
FOREIGN KEY (MAVT) REFERENCES VATTU (MAVT);

INSERT INTO VATTU VALUES
('VT01', 'GACH ', 'VIEN', 100000),
('VT02', 'XI-MANG', 'BAO', 3000);

INSERT INTO HDBAN VALUES
('HD01', '2022-9-11', 'TRAN NGOC HAI'),
('HD02', '2022-9-16', 'VO HOAI THANH');

INSERT INTO HANGXUAT VALUES
('HD01', 'VT01', 7000, 500),
('HD01', 'VT02', 35000, 30),
('HD02', 'VT01', 7200, 100),
('HD02', 'VT02', 38000, 40);


-- CÂU 2
SELECT TOP 1
MAHD, SUM(SLBAN * DONGIA) AS N'T?ng Ti?n'
FROM HANGXUAT
GROUP BY MAHD
ORDER BY SUM(SLBAN * DONGIA) Desc;

-- CÂU 3
CREATE FUNCTION f3 (
    @MAHD varchar(10)
)
RETURNS TABLE
AS
RETURN
    SELECT 
        HX.MAHD,
        HD.NGAYXUAT,
        HX.MAVT,
        HX.DONGIA,
        HX.SLBAN,  
        CASE
            WHEN WEEKDAY(HD.NGAYXUAT) = 0 THEN N'Th? hai'            
            WHEN WEEKDAY(HD.NGAYXUAT) = 1 THEN N'Th? ba'
            WHEN WEEKDAY(HD.NGAYXUAT) = 2 THEN N'Th? t?'
            WHEN WEEKDAY(HD.NGAYXUAT) = 3 THEN N'Th? n?m'
            WHEN WEEKDAY(HD.NGAYXUAT) = 4 THEN N'Th? sáu'
            WHEN WEEKDAY(HD.NGAYXUAT) = 5 THEN N'Th? b?y'
            ELSE N'Ch? nh?t'
        END AS NGAYTHU
    FROM HANGXUAT HX
    INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @MAHD;

-- CÂU 4
CREATE PROCEDURE p4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;